spring:
  application:
    name: mutildatasource
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3308/demo?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        slave_1:
          url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        durid:
          initial-size: 1
          max-active: 20
          min-idle: 1
          max-wait: 60000
  #    url: jdbc:mysql://localhost/demo?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true



server:
  port: 8086


logging:
  level:
    com.zwl.dao: debug


mybatis-plus:
  configuration:
    call-setters-on-nulls: true
  check-config-location: false
  type-aliases-package: com.zwl.entity
  mapper-locations: classpath:/mapper/*.xml