server:
  port: 8112

spring:
  application:
    name: rocketmq-provider

rocketmq:
  producer:
    #消息组
    group: my-group
    #启动消息链路
    enable-msg-trace: true
    customized-trace-topic: my-trace-topic
    #配置ACL
    access-key: AK
    secret-key: SK
  name-server: 127.0.0.1:9876