spring:
  application:
    name: securityApp
  datasource:
    url: jdbc:mysql://localhost:3306/security?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  security:
    user:
      name: admin
      password: 123456
server:
  port: 9090

