spring:
  application:
    name: dubbo-server
server:
  port: 8083
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    simplified: true
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 1000
    token: true