spring:
  application:
    name: mongodb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo
      auto-index-creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8085

logging:
  level:
    org.springframework.data.mongodb.core: debug