spring:
  application:
    name: redisApp
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        enabled: true
        max-wait: 1000
        max-active: 50
        min-idle: 10
        max-idle: 20
      shutdown-timeout: 1000
    connect-timeout: 6000
server:
  port: 8088
