spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8090

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.zwl.domain
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

#dubbo配置
dubbo:
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
    qos-enable: false
    version: 1.0.0
  registry:
    id: ${spring.application.name}-registry
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    check: true
    simplified: true
  config-center:
    address: nacos://127.0.0.1:8848
    check: true
    username: nacos
    password: nacos
  metadata-report:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  provider:
    timeout: 1000
    version: 1.0.0
  consumer:
    timeout: 1000
    version: 1.0.0
  scan:
    base-packages: com.zwl

#seata配置
seata:
  enabled: true
  data-source-proxy-mode: AT
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      order-service-group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: nacos
    nacos:
      cluster: default
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: seata
      group: SEATA_GROUP
      username: nacos
      password: nacos
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace: seata
#      group: service.vgroupMapping.order-service-group
#      username: nacos
#      password: nacos

